# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 09:59
from __future__ import unicode_literals

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blogs.models.upload_path),
        ),
    ]
